#!/usr/bin/env python
# Name:
# Student number:
"""
This script visualizes data obtained from a .csv file
"""

import csv
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Global constants for the input file, first and last year
INPUT = "movies.csv"
START_YEAR = 2008
END_YEAR = 2018

if __name__ == "__main__":

    data = pd.read_csv(INPUT)
    print(data)
